### ISSUE TITLE
Upgrade actions/checkout.

### ISSUE THREAD

**Issue by CodeMan99** [devcontainers/feature-starter#24]
Upgrade the [github workflows](https://github.com/devcontainers/feature-starter/tree/27473c035e5cb5e1be9c83e674e4bcb225879034/.github/workflows) to use [`actions/checkout@v3`](https://github.com/actions/checkout).

Right now `actions/checkout@v2` is used and creates the following warnings.

> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by samruddhikhandale** [comment]
Thanks! Updated with https://github.com/devcontainers/feature-starter/commit/aac19152fc12052fa33f79e1041ae6b1b624c395 🚀
