### ISSUE TITLE
Updating base image

### ISSUE THREAD

**Issue by joshuanianji** [devcontainers/feature-starter#55]
Hello! Now that [javascript-node v1](https://github.com/devcontainers/images/blob/main/src/javascript-node/history/1.0.0.md) is released, I'm just wondering if you had plans to update the base image.

For about 99% of my use cases the current image is fine, but I just encountered an issue that required using a newer version of libc for one of my projects so I guess it'll be nice to update the libraries for everyone.

**Comment by joshspicer** [comment]
Hey @joshuanianji ! I've linked a PR, let me know if that was what you were looking for.
