### ISSUE TITLE
**Release Notes Persisted**

### ISSUE THREAD

**Issue by Macyoutuber** [devcontainers/feature-starter#57]
**Release Notes Persisted**

> Added the ability to send HTTP headers with `session.downloadURL()`.

_Originally posted by @release-clerk in https://github.com/electron/electron/pull/38870#issuecomment-1622459059_

**Comment by bamurtaugh** [comment]
Thanks for opening. Closing as this issue doesn't seem related to dev containers, but please feel free to let us know if it is!
