### ISSUE TITLE
No compile instructions

### ISSUE THREAD

**Issue by worthy7** [devcontainers/feature-starter#73]
I tried to make a feature via this starter.

1. Download the template
2. Make a new feature or change the ID of color or hello feature
3. Error `Blob /tmp/features-output-1699945273175/devcontainer-feature-.......tgz does not exist.`

Via this comment https://github.com/devcontainers/features/issues/752#issuecomment-1811349223 it seems I should also have compiled something but I don't see those instructions in this feature-starter readme. So please can we make it clearer?

**Comment by joshspicer** [comment]
Hey there!  This repo utilizes a GitHub action [following these steps in the README](https://github.com/devcontainers/feature-starter?tab=readme-ov-file#publishing) for publishing.  We also provide [this guide](https://containers.dev/guide/author-a-feature), although the steps are quite similar.   "Under the hood" this GitHub action invokes the `devcontainer features publish` command, which has the arguments as shown below

```
[~]$ devcontainer features publish --help
devcontainer features publish <target>

Package and publish Features

Positionals:
  target
           Package and publish features at provided [target] (default is cwd), where [target] is either:
              1. A path
           to the src folder of the collection with [1..n] features.
              2. A path to a single feature that contains a d
           evcontainer-feature.json.
                                                                                      [string] [required] [default: "."]

Options:
      --help       Show help                                                                                   [boolean]
      --version    Show version number                                                                         [boolean]
  -r, --registry   Name of the OCI registry.                                               [string] [default: "ghcr.io"]
  -n, --namespace  Unique indentifier for the collection of features. Example: <owner>/<repo>        [string] [required]
      --log-level  Log level.                                      [choices: "info", "debug", "trace"] [default: "info"]
```

Hope this is helpful! If you're still stuck, please provide step-by-step instructions so we can better assist you.
