### ISSUE TITLE
Devcontainer fails to start in VSCode on my M1 Macbook Pro

### ISSUE THREAD

**Issue by husterk** [devcontainers/feature-starter#76]
This default devcontainer template in this repo fails to load the devcontainer in VSCode on my M1 Macbook Pro. It seems to get into some kind of cycle where it knows that a devcontainer is available but it can't use it. The fix that I ran across on StackOverflow was to add an `initializeCommand` to the `devcontainer.json` file. This resolved the issue for me. Should this fix be incorporated into this template?

**Fix**
```
"initializeCommand": "echo 'Initializing devcontainer'",
```

**Comment by eljog** [comment]
Thank you for opening this issue.
Could you please the error message and logs/screenshots to help us understand the problem better?

**Comment by husterk** [comment]
I attempted to reproduce this issue and I am no longer able to. It's possible that an update to VSCode resolved the issue.
