### ISSUE TITLE
Request: Deno support

### ISSUE THREAD

**Issue by utenma** [devcontainers/feature-starter#82]
adding node is possible

```
"features": {
	"ghcr.io/devcontainers/features/node:latest": {}
}
```

would be nice to have deno as well

**Comment by joshspicer** [comment]
While we do not maintain a "first-party" deno Feature, several members of the community have provided their own deno Features.  Please check out https://containers.dev/features (searching "deno")

Note that this repo is a template/starting point for self-authoring your own Dev Container Features.  That link provided above and https://github.com/devcontainers/features may have more of what you're looking for!
